[package]
name = "prize-meta"
version = "0.0.0"
authors = ["You"]
edition = "2018"
publish = false

[dependencies.prize]
path = ".."

[dependencies.elrond-wasm]
version = "0.29.3"

[dependencies.elrond-wasm-debug]
version = "0.29.3"
